Repository rancherlabs/application-collection-extension, pull requests merged in 2025-05, with the labels that each got.

#18 Add selector for kubernetes context in the settings page
  ui/src/clients/backend.ts
  ui/src/clients/kubectl.ts
  ui/src/pages/SettingsPage/index.tsx
Labels: feature

#19 Use target arch for helm/kubectl binaries
  Dockerfile
Labels: bug

#26 Password input type for access token
  ui/src/pages/SettingsPage/components/AuthenticationForm.tsx
Labels: enhancement

#31 Remove unnecessary single quote wrapping in helm charts description
  ui/src/clients/helm.ts
Labels: bug
